name = "mosir-portal"
compatibility_date = "2024-01-01"

[env.production]
name = "mosir-portal-production"
route = "app.e-mosir.pl/*"
zone_name = "e-mosir.pl"

[env.staging]
name = "mosir-portal-staging"
route = "staging.app.e-mosir.pl/*"
zone_name = "e-mosir.pl"

[build]
command = "npm run build"
cwd = "."


