version: "3.9"

networks:
  proxy:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik-proxy}

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: mosir-portal:local
    container_name: mosir-portal-app
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      proxy:
        aliases:
          - app
          - mosir-portal-app
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK:-traefik-proxy}
      # Serve over HTTP (for Cloudflare proxy Flexible mode)
      - traefik.http.routers.mosir.rule=Host(`${APP_HOSTNAME}`)
      - traefik.http.routers.mosir.entrypoints=web
      - traefik.http.services.mosir.loadbalancer.server.port=3000
